const mongoose = require("mongoose");
const { Schema } = mongoose;
import { db2 } from './../../databaseMongo';


const encuesta1Schema = new Schema({
    codigo_encuesta: {type: String, required:true, unique:true},
    codigo_encuestador: {type: String, required:true},
    codigo_per: {type: String, required:true},
    fecha: {type: String, required: true},
    horaInicio:{type: String, required: true},
    horaFin: {type: String, required: true},
    foto:{type: String, required: false},
    tipoVivienda: {type: String, required: false},
    otroTipoVivienda: {type: String, required: false},
    numeroPisos: {type: String, required: false},
    techo:{type: String, required: false},
    paredes:{type: String, required: false},
    piso:{type:String, required: false},
    vivienda:{type:String, required:false},
    numeroPersonas:{type:String, required:false},
    problemasEstomacales:{type:String, required:false},
    tipoProblemasEstomacales:{type:String, required:false},
    otroProblemasEstomacales:{type:String, required:false},
    enfermedadPiel:{type:String, required:false},
    tipoEnfermedadPiel:{type:String, required:false},
    otraEnfermedadPiel:{type:String, required:false},
    abastecimientoAgua:{type:String, required:false},
    nombreRio:{type:String, required:false},
    otroAbastecimientoAgua:{type:String, required:false},
    sisternaTanque:{type:String, required:false},
    desdeDondeLlegaAgua:{type:String, required:false},
    origenAguaBeber:{type:String, required:false},
    tratamientoOrigenAgua:{type:String, required:false},
    usoAgua:{type:String, required:false},
    capacidadTanque:{type:String, required:false},
    capacidadSisterna:{type:String, required:false},
    frecuenciaLimpieza: { type: String, required: false },
    frecuenciaCloracion: { type: String, required: false },
    otroFrecuenciaCloracion: { type: String, required: false },
    dosisCloracion: { type: String, required: false },
    otroDosisCloracion: { type: String, required: false },
    mascotas_animal: { type: String, required: false },
    consumo_animal:{ type: String, required: false },
    venta_animal: { type: String, required: false },
    ornamentales_riego: { type: String, required: false },
    consumo_riego: { type: String, required: false },
    venta_riego: { type: String, required: false },
    cantHombres: { type: String, required: false },
    cantMujeres: { type: String, required: false },
    cantNinos: { type: String, required: false },
    cantDiscapacidad: { type: String, required: false },
    nombre_persona:{type: String, required:true},
    dir_persona:{type: String, required:true},
    com_persona:{type: String, required:true},
    barr_persona:{type: String, required:true},
    jun_ag_persona:{type: String, required:true},
    edad_persona:{type: String, required:true},
    sexo_persona:{type: String, required:true},
    longitud_persona:{type: String, required:true},
    latitud_persona:{type: String, required:true}
});

module.exports = db2.model("Encuesta1", encuesta1Schema);
